//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackJobAPI.TrackJobLineService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDetailXmlField;
        
        private FaultMessageList[] faultMessageListArrayField;
        
        private InfologMessage[] infologMessageListField;
        
        private string stackTraceField;
        
        private int xppExceptionTypeField;
        
        private bool xppExceptionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CustomDetailXml {
            get {
                return this.customDetailXmlField;
            }
            set {
                this.customDetailXmlField = value;
                this.RaisePropertyChanged("CustomDetailXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public FaultMessageList[] FaultMessageListArray {
            get {
                return this.faultMessageListArrayField;
            }
            set {
                this.faultMessageListArrayField = value;
                this.RaisePropertyChanged("FaultMessageListArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
        public InfologMessage[] InfologMessageList {
            get {
                return this.infologMessageListField;
            }
            set {
                this.infologMessageListField = value;
                this.RaisePropertyChanged("InfologMessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int XppExceptionType {
            get {
                return this.xppExceptionTypeField;
            }
            set {
                this.xppExceptionTypeField = value;
                this.RaisePropertyChanged("XppExceptionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XppExceptionTypeSpecified {
            get {
                return this.xppExceptionTypeFieldSpecified;
            }
            set {
                this.xppExceptionTypeFieldSpecified = value;
                this.RaisePropertyChanged("XppExceptionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string documentOperationField;
        
        private FaultMessage[] faultMessageArrayField;
        
        private string fieldField;
        
        private string serviceField;
        
        private string serviceOperationField;
        
        private string serviceOperationParameterField;
        
        private string xPathField;
        
        private string xmlLineField;
        
        private string xmlPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentOperation {
            get {
                return this.documentOperationField;
            }
            set {
                this.documentOperationField = value;
                this.RaisePropertyChanged("DocumentOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FaultMessage[] FaultMessageArray {
            get {
                return this.faultMessageArrayField;
            }
            set {
                this.faultMessageArrayField = value;
                this.RaisePropertyChanged("FaultMessageArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServiceOperation {
            get {
                return this.serviceOperationField;
            }
            set {
                this.serviceOperationField = value;
                this.RaisePropertyChanged("ServiceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ServiceOperationParameter {
            get {
                return this.serviceOperationParameterField;
            }
            set {
                this.serviceOperationParameterField = value;
                this.RaisePropertyChanged("ServiceOperationParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string XmlLine {
            get {
                return this.xmlLineField;
            }
            set {
                this.xmlLineField = value;
                this.RaisePropertyChanged("XmlLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string XmlPosition {
            get {
                return this.xmlPositionField;
            }
            set {
                this.xmlPositionField = value;
                this.RaisePropertyChanged("XmlPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfologMessageType infologMessageTypeField;
        
        private bool infologMessageTypeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfologMessageType InfologMessageType {
            get {
                return this.infologMessageTypeField;
            }
            set {
                this.infologMessageTypeField = value;
                this.RaisePropertyChanged("InfologMessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfologMessageTypeSpecified {
            get {
                return this.infologMessageTypeFieldSpecified;
            }
            set {
                this.infologMessageTypeFieldSpecified = value;
                this.RaisePropertyChanged("InfologMessageTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class KeyField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyField[] keyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyField[] KeyData {
            get {
                return this.keyDataField;
            }
            set {
                this.keyDataField = value;
                this.RaisePropertyChanged("KeyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="TrackJobLineService.STMTrackJobLineAPIService")]
    public interface STMTrackJobLineAPIService {
        
        // CODEGEN: Generating message contract since the wrapper name (STMTrackJobLineAPIServiceDeleteRequest) of message STMTrackJobLineAPIServiceDeleteRequest does not match the default value (delete)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/delete", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackJobAPI.TrackJobLineService.AifFault), Action="http://tempuri.org/STMTrackJobLineAPIService/deleteAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteResponse delete(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/delete", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/deleteResponse")]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteResponse> deleteAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMTrackJobLineAPIServiceReadRequest) of message STMTrackJobLineAPIServiceReadRequest does not match the default value (read)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/read", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/readResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackJobAPI.TrackJobLineService.AifFault), Action="http://tempuri.org/STMTrackJobLineAPIService/readAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadResponse read(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/read", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/readResponse")]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadResponse> readAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMTrackJobLineAPIServiceFindRequest) of message STMTrackJobLineAPIServiceFindRequest does not match the default value (find)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/find", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackJobAPI.TrackJobLineService.AifFault), Action="http://tempuri.org/STMTrackJobLineAPIService/findAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindResponse find(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/find", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/findResponse")]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindResponse> findAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMTrackJobLineAPIServiceUpdateRequest) of message STMTrackJobLineAPIServiceUpdateRequest does not match the default value (update)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/update", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackJobAPI.TrackJobLineService.AifFault), Action="http://tempuri.org/STMTrackJobLineAPIService/updateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateResponse update(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/update", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/updateResponse")]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateResponse> updateAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (STMTrackJobLineAPIServiceCreateRequest) of message STMTrackJobLineAPIServiceCreateRequest does not match the default value (create)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/create", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackJobAPI.TrackJobLineService.AifFault), Action="http://tempuri.org/STMTrackJobLineAPIService/createAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateResponse create(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STMTrackJobLineAPIService/create", ReplyAction="http://tempuri.org/STMTrackJobLineAPIService/createResponse")]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateResponse> createAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private string languageField;
        
        private string logonAsUserField;
        
        private string messageIdField;
        
        private string partitionKeyField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertyBagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LogonAsUser {
            get {
                return this.logonAsUserField;
            }
            set {
                this.logonAsUserField = value;
                this.RaisePropertyChanged("LogonAsUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string PartitionKey {
            get {
                return this.partitionKeyField;
            }
            set {
                this.partitionKeyField = value;
                this.RaisePropertyChanged("PartitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] PropertyBag {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceDeleteRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceDeleteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TrackJobAPI.TrackJobLineService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList;
        
        public STMTrackJobLineAPIServiceDeleteRequest() {
        }
        
        public STMTrackJobLineAPIServiceDeleteRequest(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceDeleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceDeleteResponse {
        
        public STMTrackJobLineAPIServiceDeleteResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI")]
    public partial class AxdSTMTrackJobLineAPI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<AxdEnum_boolean> clearNilFieldsOnUpdateField;
        
        private bool clearNilFieldsOnUpdateFieldSpecified;
        
        private System.Nullable<AxdEnum_XMLDocPurpose> docPurposeField;
        
        private bool docPurposeFieldSpecified;
        
        private string senderIdField;
        
        private AxdEntity_STMTrackJobLine[] sTMTrackJobLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<AxdEnum_boolean> ClearNilFieldsOnUpdate {
            get {
                return this.clearNilFieldsOnUpdateField;
            }
            set {
                this.clearNilFieldsOnUpdateField = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearNilFieldsOnUpdateSpecified {
            get {
                return this.clearNilFieldsOnUpdateFieldSpecified;
            }
            set {
                this.clearNilFieldsOnUpdateFieldSpecified = value;
                this.RaisePropertyChanged("ClearNilFieldsOnUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<AxdEnum_XMLDocPurpose> DocPurpose {
            get {
                return this.docPurposeField;
            }
            set {
                this.docPurposeField = value;
                this.RaisePropertyChanged("DocPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocPurposeSpecified {
            get {
                return this.docPurposeFieldSpecified;
            }
            set {
                this.docPurposeFieldSpecified = value;
                this.RaisePropertyChanged("DocPurposeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("STMTrackJobLine", Order=3)]
        public AxdEntity_STMTrackJobLine[] STMTrackJobLine {
            get {
                return this.sTMTrackJobLineField;
            }
            set {
                this.sTMTrackJobLineField = value;
                this.RaisePropertyChanged("STMTrackJobLine");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_boolean {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_XMLDocPurpose {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Proforma,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI")]
    public partial class AxdEntity_STMTrackJobLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _DocumentHashField;
        
        private System.Nullable<System.DateTime> actEndDateField;
        
        private bool actEndDateFieldSpecified;
        
        private System.Nullable<System.DateTime> actStartDateField;
        
        private bool actStartDateFieldSpecified;
        
        private System.Nullable<int> delayField;
        
        private bool delayFieldSpecified;
        
        private System.Nullable<int> delayPlanField;
        
        private bool delayPlanFieldSpecified;
        
        private string operNameField;
        
        private string operNoField;
        
        private System.Nullable<int> planDaysField;
        
        private bool planDaysFieldSpecified;
        
        private System.Nullable<System.DateTime> planEndDateField;
        
        private bool planEndDateFieldSpecified;
        
        private System.Nullable<System.DateTime> planStartDateField;
        
        private bool planStartDateFieldSpecified;
        
        private System.Nullable<long> recIdField;
        
        private bool recIdFieldSpecified;
        
        private System.Nullable<int> recVersionField;
        
        private bool recVersionFieldSpecified;
        
        private string remarkField;
        
        private string sideDesignField;
        
        private string stmTrackIdField;
        
        private string typeDesignField;
        
        private string userIdField;
        
        private string userNameField;
        
        private string classField;
        
        private AxdEnum_AxdEntityAction actionField;
        
        private bool actionFieldSpecified;
        
        public AxdEntity_STMTrackJobLine() {
            this.classField = "entity";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _DocumentHash {
            get {
                return this._DocumentHashField;
            }
            set {
                this._DocumentHashField = value;
                this.RaisePropertyChanged("_DocumentHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> ActEndDate {
            get {
                return this.actEndDateField;
            }
            set {
                this.actEndDateField = value;
                this.RaisePropertyChanged("ActEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActEndDateSpecified {
            get {
                return this.actEndDateFieldSpecified;
            }
            set {
                this.actEndDateFieldSpecified = value;
                this.RaisePropertyChanged("ActEndDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ActStartDate {
            get {
                return this.actStartDateField;
            }
            set {
                this.actStartDateField = value;
                this.RaisePropertyChanged("ActStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActStartDateSpecified {
            get {
                return this.actStartDateFieldSpecified;
            }
            set {
                this.actStartDateFieldSpecified = value;
                this.RaisePropertyChanged("ActStartDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
                this.RaisePropertyChanged("Delay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelaySpecified {
            get {
                return this.delayFieldSpecified;
            }
            set {
                this.delayFieldSpecified = value;
                this.RaisePropertyChanged("DelaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DelayPlan {
            get {
                return this.delayPlanField;
            }
            set {
                this.delayPlanField = value;
                this.RaisePropertyChanged("DelayPlan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayPlanSpecified {
            get {
                return this.delayPlanFieldSpecified;
            }
            set {
                this.delayPlanFieldSpecified = value;
                this.RaisePropertyChanged("DelayPlanSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string OperName {
            get {
                return this.operNameField;
            }
            set {
                this.operNameField = value;
                this.RaisePropertyChanged("OperName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string OperNo {
            get {
                return this.operNoField;
            }
            set {
                this.operNoField = value;
                this.RaisePropertyChanged("OperNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> PlanDays {
            get {
                return this.planDaysField;
            }
            set {
                this.planDaysField = value;
                this.RaisePropertyChanged("PlanDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlanDaysSpecified {
            get {
                return this.planDaysFieldSpecified;
            }
            set {
                this.planDaysFieldSpecified = value;
                this.RaisePropertyChanged("PlanDaysSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> PlanEndDate {
            get {
                return this.planEndDateField;
            }
            set {
                this.planEndDateField = value;
                this.RaisePropertyChanged("PlanEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlanEndDateSpecified {
            get {
                return this.planEndDateFieldSpecified;
            }
            set {
                this.planEndDateFieldSpecified = value;
                this.RaisePropertyChanged("PlanEndDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> PlanStartDate {
            get {
                return this.planStartDateField;
            }
            set {
                this.planStartDateField = value;
                this.RaisePropertyChanged("PlanStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlanStartDateSpecified {
            get {
                return this.planStartDateFieldSpecified;
            }
            set {
                this.planStartDateFieldSpecified = value;
                this.RaisePropertyChanged("PlanStartDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<long> RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
                this.RaisePropertyChanged("RecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecIdSpecified {
            get {
                return this.recIdFieldSpecified;
            }
            set {
                this.recIdFieldSpecified = value;
                this.RaisePropertyChanged("RecIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> RecVersion {
            get {
                return this.recVersionField;
            }
            set {
                this.recVersionField = value;
                this.RaisePropertyChanged("RecVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecVersionSpecified {
            get {
                return this.recVersionFieldSpecified;
            }
            set {
                this.recVersionFieldSpecified = value;
                this.RaisePropertyChanged("RecVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string SideDesign {
            get {
                return this.sideDesignField;
            }
            set {
                this.sideDesignField = value;
                this.RaisePropertyChanged("SideDesign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string StmTrackId {
            get {
                return this.stmTrackIdField;
            }
            set {
                this.stmTrackIdField = value;
                this.RaisePropertyChanged("StmTrackId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string TypeDesign {
            get {
                return this.typeDesignField;
            }
            set {
                this.typeDesignField = value;
                this.RaisePropertyChanged("TypeDesign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AxdEnum_AxdEntityAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/sharedtypes")]
    public enum AxdEnum_AxdEntityAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        delete,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceReadRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceReadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TrackJobAPI.TrackJobLineService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList;
        
        public STMTrackJobLineAPIServiceReadRequest() {
        }
        
        public STMTrackJobLineAPIServiceReadRequest(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceReadResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI")]
        public TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI;
        
        public STMTrackJobLineAPIServiceReadResponse() {
        }
        
        public STMTrackJobLineAPIServiceReadResponse(TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            this.STMTrackJobLineAPI = STMTrackJobLineAPI;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class QueryCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CriteriaElement[] criteriaElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CriteriaElement", Order=0)]
        public CriteriaElement[] CriteriaElement {
            get {
                return this.criteriaElementField;
            }
            set {
                this.criteriaElementField = value;
                this.RaisePropertyChanged("CriteriaElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public partial class CriteriaElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceNameField;
        
        private string fieldNameField;
        
        private Operator operatorField;
        
        private string value1Field;
        
        private string value2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
                this.RaisePropertyChanged("DataSourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Operator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
    public enum Operator {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Range,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceFindRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceFindRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TrackJobAPI.TrackJobLineService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/QueryCriteria")]
        public TrackJobAPI.TrackJobLineService.QueryCriteria QueryCriteria;
        
        public STMTrackJobLineAPIServiceFindRequest() {
        }
        
        public STMTrackJobLineAPIServiceFindRequest(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.QueryCriteria QueryCriteria) {
            this.CallContext = CallContext;
            this.QueryCriteria = QueryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceFindResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI")]
        public TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI;
        
        public STMTrackJobLineAPIServiceFindResponse() {
        }
        
        public STMTrackJobLineAPIServiceFindResponse(TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            this.STMTrackJobLineAPI = STMTrackJobLineAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceUpdateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceUpdateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TrackJobAPI.TrackJobLineService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI")]
        public TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI;
        
        public STMTrackJobLineAPIServiceUpdateRequest() {
        }
        
        public STMTrackJobLineAPIServiceUpdateRequest(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList, TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            this.CallContext = CallContext;
            this.EntityKeyList = EntityKeyList;
            this.STMTrackJobLineAPI = STMTrackJobLineAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceUpdateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceUpdateResponse {
        
        public STMTrackJobLineAPIServiceUpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceCreateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceCreateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TrackJobAPI.TrackJobLineService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/STMTrackJobLineAPI")]
        public TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI;
        
        public STMTrackJobLineAPIServiceCreateRequest() {
        }
        
        public STMTrackJobLineAPIServiceCreateRequest(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            this.CallContext = CallContext;
            this.STMTrackJobLineAPI = STMTrackJobLineAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STMTrackJobLineAPIServiceCreateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class STMTrackJobLineAPIServiceCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable=false)]
        public TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList;
        
        public STMTrackJobLineAPIServiceCreateResponse() {
        }
        
        public STMTrackJobLineAPIServiceCreateResponse(TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            this.EntityKeyList = EntityKeyList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface STMTrackJobLineAPIServiceChannel : TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class STMTrackJobLineAPIServiceClient : System.ServiceModel.ClientBase<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService>, TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService {
        
        public STMTrackJobLineAPIServiceClient() {
        }
        
        public STMTrackJobLineAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public STMTrackJobLineAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STMTrackJobLineAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STMTrackJobLineAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteResponse TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.delete(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public void delete(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteResponse retVal = ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteResponse> TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.deleteAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteResponse> deleteAsync(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceDeleteRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadResponse TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.read(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest request) {
            return base.Channel.read(request);
        }
        
        public TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI read(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadResponse retVal = ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).read(inValue);
            return retVal.STMTrackJobLineAPI;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadResponse> TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.readAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadResponse> readAsync(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceReadRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            return ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindResponse TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.find(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest request) {
            return base.Channel.find(request);
        }
        
        public TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI find(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.QueryCriteria QueryCriteria) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindResponse retVal = ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).find(inValue);
            return retVal.STMTrackJobLineAPI;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindResponse> TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.findAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindResponse> findAsync(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.QueryCriteria QueryCriteria) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceFindRequest();
            inValue.CallContext = CallContext;
            inValue.QueryCriteria = QueryCriteria;
            return ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateResponse TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.update(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest request) {
            return base.Channel.update(request);
        }
        
        public void update(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList, TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            inValue.STMTrackJobLineAPI = STMTrackJobLineAPI;
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateResponse retVal = ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateResponse> TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.updateAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateResponse> updateAsync(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.EntityKey[] EntityKeyList, TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceUpdateRequest();
            inValue.CallContext = CallContext;
            inValue.EntityKeyList = EntityKeyList;
            inValue.STMTrackJobLineAPI = STMTrackJobLineAPI;
            return ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateResponse TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.create(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest request) {
            return base.Channel.create(request);
        }
        
        public TrackJobAPI.TrackJobLineService.EntityKey[] create(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.STMTrackJobLineAPI = STMTrackJobLineAPI;
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateResponse retVal = ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).create(inValue);
            return retVal.EntityKeyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateResponse> TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService.createAsync(TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateResponse> createAsync(TrackJobAPI.TrackJobLineService.CallContext CallContext, TrackJobAPI.TrackJobLineService.AxdSTMTrackJobLineAPI STMTrackJobLineAPI) {
            TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest inValue = new TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIServiceCreateRequest();
            inValue.CallContext = CallContext;
            inValue.STMTrackJobLineAPI = STMTrackJobLineAPI;
            return ((TrackJobAPI.TrackJobLineService.STMTrackJobLineAPIService)(this)).createAsync(inValue);
        }
    }
}
